### ISSUE TITLE
✨ Slack and JIRA Notifiers

### ISSUE THREAD

**Issue by znatty22** [d3b-center/d3b-data-transfer-pipeline#8]
- [ ] Create command group for slack
- [ ] Create command group for jira
- [ ] Implement and unit test the cmd to send a message to a slack channel to notify stakeholders of an important message
`d3b slack send-message (or create-message?) --slack-org=foo --slack-channel=bar`
- [ ] Implement and unit test the cmd to update a JIRA ticket's comments to notify stakeholders of status updates
`d3b jira update-ticket --ticket-id=foo --message=bar`
